AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  InstanceType:
    Type: String
    Description: EC2 instance type
    Default: t2.micro

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-12345678  # Replace with the desired AMI ID
      InstanceType: !Ref InstanceType
      Tags:
        - Key: Name
          Value: MyEC2Instance
        - Key: Environment
          Value: Production
        - !If
          - Condition: ShouldAddCustomTags
            Fn::Split:
              - ','
              - !Ref CustomTags
          - !Ref CustomTags
          - !Ref "AWS::NoValue"

Conditions:
  ShouldAddCustomTags: !Not [!Equals [!Ref CustomTags, ""]]
