AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  InstanceType:
    Type: String
    Description: EC2 instance type
    Default: t2.micro
  CustomTags:
    Type: CommaDelimitedList
    Description: Custom tags to apply to the EC2 instance
    Default: ''

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-12345678  # Replace with the desired AMI ID
      InstanceType: !Ref InstanceType
      Tags:
        - Key: Name
          Value: MyEC2Instance
        - Key: Environment
          Value: Production
        - Key: ${CustomTags[0]}
          Value: ${CustomTags[1]}
        - Key: ${CustomTags[2]}
          Value: ${CustomTags[3]}
        - Key: ${CustomTags[4]}
          Value: ${CustomTags[5]}
        - Key: ${CustomTags[6]}
          Value: ${CustomTags[7]}
        - Key: ${CustomTags[8]}
          Value: ${CustomTags[9]}
