AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  InstanceType:
    Type: String
    Description: EC2 instance type
    Default: t2.micro
  CustomTags:
    Type: CommaDelimitedList
    Description: Custom tags to apply to the EC2 instance
    Default: ''

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-12345678  # Replace with the desired AMI ID
      InstanceType: !Ref InstanceType
      Tags:
        - Key: Name
          Value: MyEC2Instance
        - Key: Environment
          Value: Production
        # Dynamically add custom tags based on user input
        {% for tagIndex, tagName in enumerate(CustomTags[::2]) %}
        - Key: !Ref 'CustomTags[${tagIndex * 2}]'
          Value: !Ref 'CustomTags[${tagIndex * 2 + 1}]'
        {% endfor %}
